### ISSUE TITLE
Use fast_gelu when fast_math enabled

### ISSUE THREAD

**Issue by pfultz2** [ROCm/AMDMIGraphX#1083]
This should probably be done in simplify_algebra. There is already the [`gelu_tanh`](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/include/migraphx/match/gelu_tanh.hpp#L43) matcher which can find gelu from its decomposed operators.

**Comment by causten** [comment]
First test to see if this change is now faster.

**Comment by bpickrel** [comment]
I will take this one but can we have a description of the issue?

**Comment by pfultz2** [comment]
So there are two versions of gelu: `gelu_tanh` and `gelu_erf`. Using `erf` should be faster(although less accurate), but we first need to investigate if its faster. If its faster we need to find `gelu_tanh` and replace it with `gelu_erf` only when `fast_math` is enabled.

To investigate the performance, it would be best to create onnx files with both versions and time them, but we need to make sure we are calling the float version of `erf` in [math.hpp](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/kernels/include/migraphx/kernels/math.hpp). @kahmed10 Can you help with creating these onnx files?

**Comment by bpickrel** [comment]
The real task for this issue:  Move the matcher from fuse_ops to simplify_algebra, update replacement too.  The matcher in fuse_ops.cpp already does the fast_math check.  line 400

**Comment by pfultz2** [comment]
> update replacement too.

Yea, the replacement wont be done as a single operator. You will need to insert multiple operators. You can use the device function [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/device/gelu.cpp#L15) as reference for the formula.

**Comment by bpickrel** [comment]
I'm starting to have a concern about unit testing for this and other simplify_algebra features, that there's no way to test the operation of struct find_gelu separately from all the other simplify_algebra structs.  I just spent quite a bit of time debugging a test for find_gelu that failed, because it was hard to even tell that the test inputs weren't being used.  The background:  find_gelu and other structs are defined in simplify_algebra.cpp which means I can't include a header file to instantiate one from the test program.    The only way to run find_gelu::apply() is via simplify_algebra::apply() which will run ALL of the structs' apply() methods and can be expected to match the input instruction list in more than one way.  The only way right now that I can verify an expected find_gelu test result is by looking at the contents of the instruction list after all those matchers have been applied.  Such a test becomes invalid if any of the matchers are changed; new ones added; or even if their calling order is changed.  At worst, we'll break the functionality of a matcher and never know it; at best, any change at all to simplify_algebra will require days of rewriting all the tests whose results are coupled to its internal logic.  This contradicts the basic definition of unit tests, which is that they test low-level units of code in isolation.

How urgently are we committed to unit testability of simplify_algebra?  Possible solutions I can think of include moving all the struct definitions like gelu_tanh to the header file so they can be instantiated in isolation, or making the structs members of simplify_algebra so we can query them within the test instance (that is, member code members that exists only for unit testing).  Any other ideas?
