### ISSUE TITLE
Verify tests have threshold of 0.078 for FP16 tests

### ISSUE THREAD

**Issue by umangyadav** [ROCm/AMDMIGraphX#1708]
Threshold should be in the range of 0.001. 

https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/f92e799445b367ddfec46241b3700fd4cd4a894d/src/include/migraphx/verify.hpp#L192

**Comment by pfultz2** [comment]
> Threshold should be in the range of 0.001.

Why? The epsilon for half is 0.000976562, which is very close to this number. That leaves very little room for accumulative errors when summation is done in a different order.

For fp32 we use a threshold of `10^-6`, but the mantissa is `2^14` times bigger. So `10^-6 * 2^14 = 0.016384` which seems to be a more reasonable threshold. We are still using a higher threshold, but we could change the default tolerance to 16 instead of 80.

**Comment by umangyadav** [comment]
As I understand, it is still using RMS range.  Generally for the models we use  `np.allclose` which uses element-wise comparsion. Why not just do element-wise comparison with similar mechanisms of `rtol` and `atol`. 
That way we don't have to worry about the order of the computation.

**Comment by umangyadav** [comment]
Also 
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/f92e799445b367ddfec46241b3700fd4cd4a894d/src/include/migraphx/verify.hpp#L183

It is normalized by `n`.

Then, 
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/f92e799445b367ddfec46241b3700fd4cd4a894d/src/include/migraphx/verify.hpp#L196

Compares the normalized value with the threshold (which is higher).  So most likely it will pass.

**Comment by umangyadav** [comment]
Closing this one for now.
