### ISSUE TITLE
LSTM verify test fails for gpu when inputs are transposed

### ISSUE THREAD

**Issue by nives-vukovic** [ROCm/AMDMIGraphX#2441]
During testing of LSTM operator with non-standard layout (layout=1), new verify tests have been created to recreate a scenario where input shapes have to be transposed before calling `lstm`. Verify test where direction attribute is `migraphx::op::rnn_direction::bidirectional` and sequence_lens attribute is not undefined fails. When `eliminate_contiguous{"gpu::contiguous"}` is commented out, all tests pass.
Reported error:
FAILED: gpu
RMS Error: 0.202458
Max diff: 0.426603
Mismatch at 5: -0.193233 != 0.0861849

Detailed log with prints and MIGRAPHX_TRACE_ELIMINATE_CONTIGUOUS enabled is attached.
[log.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/13335523/log.txt)

Implementation of the verify test that fails
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/commit/00c630eac3ab3ff520e02acca1f70f33c4f74f1a#diff-8ace7718bde6e167436445e55de9abc1aa7db218fa1723d4a3b98956200a71d5

Same error appears when similar scenario is created for GRU and RNN operator.

cc @causten

**Comment by ppanchad-amd** [comment]
Hi @nives-vukovic. Apologies for the lack of response. An internal ticket has been created to investigate your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @nives-vukovic. Thank you for reaching out! Are you still experiencing the issue with the latest, or were you find out why the issue occurs? Thanks!

**Comment by tcgu-amd** [comment]
@nives-vukovic Looks like this issue is out of date. Did a bit of digging and seems like this is an issue that was part of an attempt to add "layout" attribute to the lstm operator. The effort has been dropped as per https://github.com/ROCm/AMDMIGraphX/pull/2343#discussion_r1386781446, which would render this issue also obsolete. 

This ticket will be closed. Please feel free to reopen & update the reproducer for further assitance. 

Thanks!!
