### ISSUE TITLE
Dynamic shape with unspecified range

### ISSUE THREAD

**Issue by CharlieL7** [ROCm/AMDMIGraphX#2674]
There are operators in MIGraphX that can produce dynamic shapes with an unspecified range such as `allocate` or `resize`. For these operators we have been using `dynamic_dimension`s with range `{0, max_int}` as a stand-in for an unknown range. This leads to a clarity issue and an issue with the `shape.element_space()` calculation for rank > 1.
* We need a way to specify that a dimension is fully unknown without a specific minimum or maximum.
* This will need logic changes throughout the dynamic shape handling.

**Comment by bpickrel** [comment]
My first Verify test for PR #2657 failed because a program containing an indefinite-sized dynamic shape caused the GPU to run out of memory.  Even relatively modest ranges of `{0,64}, {0,64}, {0, 4096}, {0, 4096}`  (which multiplies out to 16G; not known how many bytes this equates to) lead to a failure to load the program on aus-navi3x-02.  This tells us the current unspecified range logic is not just unclear but unworkable.

**Comment by pfultz2** [comment]
Why cant `{0, max_int}` mean an unspecified range? And what about the cases where the min is known but the max is not known? We are never going to use `max_int` as a real upper limit so we can interpret it as meaning the upper range is not known. 

> This leads to a clarity issue and an issue with the shape.element_space() calculation for rank > 1.

And for that case we should just return `max_int`.

**Comment by pfultz2** [comment]
> My first Verify test for PR https://github.com/ROCm/AMDMIGraphX/pull/2657 failed because a program containing an indefinite-sized dynamic shape caused the GPU to run out of memory.

I dont understand why you are trying to run dynamic shapes on the gpu. That isn't supported.

Even more so this seems irrelevant to this issue. Even if we can represent an unknown dimension we have no way to allocate a buffer for it because we dont know its size.

**Comment by CharlieL7** [comment]
Clipping is a lot less work, so I'm going to make `shape.element_space()` do that for now.

**Comment by bpickrel** [comment]
> > My first Verify test for PR #2657 failed because a program containing an indefinite-sized dynamic shape caused the GPU to run out of memory.
> 
> I dont understand why you are trying to run dynamic shapes on the gpu. That isn't supported.

For starters, that is still a draft PR so it makes sense to try a test to see what happens.  What I learned is that 

1.  the test does do the Resize pass substitution and run the results on the GPU; 
2.  the test turned up a memory error and so is proven useful.

This test is the only way I know of to run the results of the Resize matcher on the GPU and compare its outputs with the ref. case.  Even though it doesn't use the Resize op on the GPU, the result values should be the same.


> 
> Even more so this seems irrelevant to this issue. Even if we can represent an unknown dimension we have no way to allocate a buffer for it because we dont know its size.

Because we're solving the wrong problem.  The entire purpose of dynamic shapes is to put meaningful inputs on the GPU at runtime, so we shouldn't be focusing on individual handling bugs without first having a clear understanding of what we expect to happen when the program is loaded on the GPU.  The fact that the Verify test failed so easily tells me we don't.

**Comment by CharlieL7** [comment]
Resolved by doing the clip in #2675.
