### ISSUE TITLE
Create a compiler pass that tracks shape aliasing operations to find NOP

### ISSUE THREAD

**Issue by CharlieL7** [ROCm/AMDMIGraphX#2811]
From the 22 Feb 2024 performance model review of Distilgpt2:

Replace no-op `transpose -> reshape_lazy`

```
@344 = load[offset=1069056,end=1603584](@1) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.0004241ms, 1%
@345 = transpose[permutation={0, 2, 1, 3}](@342) -> half_type, {1, 348, 12, 64}, {267264, 768, 64, 1}, target_id=0: 0.00044634ms, 1%
@346 = reshape_lazy[dims={348, 768}](@345) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.00045542ms, 1%
@347 = gpu::gemm[alpha=1,beta=0,compute_fp32=1,trans_batch=0,solution_idx=0](@346,@343,@344) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.0466007ms, 2%
```

Should be able to get rid of the `transpose` since we're reverting the shape back to standard.
Cleans up the IR for later possible fusions. Possibly related to the current work on the `einsum` ONNX operator parsing. 

Deliverables:
* New matcher or pass that tracks these aliasing operations and replaces them if they can be simplified.

EDIT: See later comment for more complete IR section

**Comment by pfultz2** [comment]
> Should be able to get rid of the transpose since we're reverting the shape back to standard.

What exactly is the `transpose` to be replaced with? If the `transpose` was removed the dimensions would be in the wrong order.

**Comment by CharlieL7** [comment]
I missed puting the whole IR section:
```
@342 = gpu::gemm[alpha=1,beta=0,compute_fp32=1,trans_batch=1,solution_idx=0](@338,@341,@340) -> half_type, {1, 12, 348, 64}, {267264, 64, 768, 1}, target_id=0: 0.0408614ms, 2%
@343 = hip::hip_copy_literal[id=main:@literal:17] -> half_type, {768, 768}, {768, 1}, target_id=0: 0.00053846ms, 1%
@344 = load[offset=1069056,end=1603584](@1) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.0004241ms, 1%
@345 = transpose[permutation={0, 2, 1, 3}](@342) -> half_type, {1, 348, 12, 64}, {267264, 768, 64, 1}, target_id=0: 0.00044634ms, 1%
@346 = reshape_lazy[dims={348, 768}](@345) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.00045542ms, 1%
@347 = gpu::gemm[alpha=1,beta=0,compute_fp32=1,trans_batch=0,solution_idx=0](@346,@343,@344) -> half_type, {348, 768}, {768, 1}, target_id=0: 0.0466007ms, 2%
```
The transpose is used to move the 12 and 64 dimensions together, but the original buffer already had it that way from the gemm output `@342`. So the reshape_lazy can be directly done on `@342`.

**Comment by pfultz2** [comment]
And what are you wanting to replace the `transpose` with? If you removed it it will put the dimensions in the wrong order, so what exactly are you wanting the IR to look like?

Also, most likely this was a transpose->contiguous->reshape_lazy originally and then contiguous was removed by [`find_contiguous_tranpose_gemm`](https://github.com/ROCm/AMDMIGraphX/blob/develop/src/targets/gpu/fuse_ops.cpp#L679) which transposes the output of the gemm in memory so that the transpose will make it contiguous for reshape_lazy allowing the contiguous to be removed.

**Comment by CharlieL7** [comment]
I'm thinking to remove the `transpose` and have the `gemm` output directly go into `reshape_lazy`. It shouldn't make much of a difference performance-wise, because `transpose` is just a shape aliasing instruction. But it looks weird to me to have two shape aliasing instructions back-to-back that basically just do the one operation of merging the last two dimensions.

**Comment by pfultz2** [comment]
> I'm thinking to remove the transpose and have the gemm output directly go into reshape_lazy.

But then we would need to add a permutation attribute to the `gemm` operator(or other operators that this would happen to).

I dont think we should make all the operators to do an implicit tranpose. Transpose is just an aliasing operator so there is very little cost to having it and it simplifies the implementation of operators. Its the same reason we dont do implicit broadcasting. 

> But it looks weird to me to have two shape aliasing instructions back-to-back

I dont see the issue here, or why it looks weird. Each aliasing instruction is doing something unique. And I dont see what we gain by removing these aliasing operators either. 

> that basically just do the one operation of merging the last two dimensions.

Its not merging the last two dimensions, its merging the dimension at axis 1 with the last dimension.

**Comment by CharlieL7** [comment]
I agree with removing the `transpose` probably not having a significant performance effect.

> Its not merging the last two dimensions, its merging the dimension at axis 1 with the last dimension.

I'm pretty sure we just have a communication difference here. The output of the `gemm` is `half_type, {1, 12, 348, 64}, {267264, 64, 768, 1}`, which means that the output buffer is equivalent to the one with a lens and strides of `{1, 348, 12, 64}, {267264, 768, 64, 1}`. From my point of view, all we're doing is traversing the output buffer as if the last two dimensions are merged.

Going to close this issue because it probably doesn't have a deliverable that's worth the time implementing. This discussion might be valuable in the future though.
