### ISSUE TITLE
[Issue]: MIGraphX Python module cannot find attribute

### ISSUE THREAD

**Issue by xuantengh** [ROCm/AMDMIGraphX#2956]
### Problem Description

I've compiled mgx from source with the following CMake config:
```bash
cmake -S . -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_PREFIX_PATH="$ROCM_INSTALL_PREFIX;$CONDA_PREFIX/lib/python3.11/site-packages/pybind11" \
  -DCMAKE_INSTALL_PREFIX=$ROCM_INSTALL_PREFIX \
  -DCMAKE_CXX_COMPILER="$ROCM_INSTALL_PREFIX/bin/clang++" \
  -DCMAKE_CXX_FLAGS="-I $ROCM_INSTALL_PREFIX/include" \
  -DGPU_TARGETS=$ROCM_GPU_ARCH -DBUILD_TESTING=OFF \
  -DMIGRAPHX_ENABLE_GPU=ON -DMIGRAPHX_USE_COMPOSABLEKERNEL=OFF -DMIGRAPHX_ENABLE_MLIR=OFF
```
where `ROCM_INSTALL_PREFIX` is where the ROCm installed, and `CONDA_PREFIX` is the Conda venv for Python.

After successfully compilation and install, I'm trying to run the Python demo with `PYTHONPATH=$ROCM_INSTALL_PREFIX python3 example.py` from [here](https://rocm.docs.amd.com/en/latest/conceptual/ai-migraphx-optimization.html#migraphx-python-api):
```python
# import migraphx and numpy
import migraphx
import numpy as np
# import and parse inception model
model = migraphx.parse_onnx("inceptioni1.onnx")
# compile model for the GPU target
model.compile(migraphx.get_target("gpu"))
# optionally print compiled model
model.print()
# create random input image
input_image = np.random.rand(1, 3, 299, 299).astype('float32')
# feed image to model, 'x.1` is the input param name
results = model.run({'x.1': input_image})
# get the results back
result_np = np.array(results[0])
# print the inferred class of the input image
print(np.argmax(result_np))
```
The errors are:
```
Traceback (most recent call last):
  File "/mnt/nvme0/home/abc/example.py", line 6, in <module>
    model = migraphx.parse_onnx("inceptioni1.onnx")
            ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'migraphx' has no attribute 'parse_onnx'
```

### Operating System

Ubuntu 22.04 Jammy Jellyfish

### CPU

AMD EPYC 7773X 64-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

**Comment by ppanchad-amd** [comment]
Hi @xuantengh, apologies for the delayed response. An internal ticket has been created to investigate your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @xuantengh. Thank you for reaching out. Currently AMDMIGraphX does not support conda/venv, so the pytorch bindings will not work properly. It should work as expected if you use python binary from /usr/bin/python3. 

Hope this helps! Since this is a known issue, I will be closing this issue. However, please feel free to ask follow up questions or re-open the issue if the problem persists.

Thanks!

**Comment by tcgu-amd** [comment]
@xuantengh Adding a bit of context here after some further investigation: since the c python binding is installed under /opt/rocm/lib, you need you make sure that conda/venv python version matches the cpython bindings manually. For example, if your ROCM_INSTALL_PREFIX is `/opt/rocm`, then under `opt/rocm/lib` you should see something like migraphx.cpython-38-x86_64-linux-gnu.so for python 3.8. Make sure the binding matches with the conda python version you are trying to run.

**Comment by thenightterorx** [comment]
I am having the same issue, except what I am trying is the sd2.1 example with the migraphx package from the repo. I have also tried downloading the migraphx.py file to my local directory and importing from there. There is no migraphx.cpython file in my /opt/rocm. Does this mean that I have to build migraphx from source?
