### ISSUE TITLE
normalize_compute_shape: CONCAT: all input dimensions should match along axis 2

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#3023]
Torch benchmarks fail.
Affected models:
Torchbench: hf_BigBird

**Comment by CharlieL7** [comment]
If you're doing a buffer copy, it should technically be possible to concatenate the two parameters directly. But that algorithm would have to be quite different.

**Comment by bpickrel** [comment]
Looks like an easy decision.  We've found several similar matcher bugs with accidental matches and more checks needing to be done.  I'd guess a general rule is that if a sequence of instructions isn't what the author of the matcher intended to match, then making the substitution is unlikely to improve performance even if it's mathematically correct.

**Comment by pfultz2** [comment]
I think it would be good to do the rewrite, since it would reduce the amount of memory we read and can improve const folding as well(I dont know if that applies in this case), but we would need to insert an extra broadcast. This is quite similar to `find_inner_broadcast`(but still different), I dont know if we can reuse anything from there.

You could copy whats done there and tweak it so it works for concat and from there we can see how we make a more generic version of the transformation.

**Comment by CharlieL7** [comment]
I'm going to put in the simple change I made so we have an immediate fix to this issue. I will make another issue tracking a rewrite for `concat` that would handle this case.
