### ISSUE TITLE
Bug in find_nested_shape_transforms

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#3579]
Repro steps:
```
# flatten_bug.py
import migraphx

p = migraphx.program()
mm = p.get_main_module()
x0 = mm.add_literal(migraphx.generate_argument(migraphx.shape(type="float_type", lens=[1, 4608, 8]), 0))
cos = mm.add_instruction(migraphx.op("cos"), [x0])
rsp = mm.add_instruction(migraphx.op("reshape", dims=[4608, 8]), [cos])
unsq = mm.add_instruction(migraphx.op("unsqueeze", axes=[2]), [rsp])
cat = mm.add_instruction(migraphx.op("concat", axis=2), [unsq, unsq])
flat = mm.add_instruction(migraphx.op("flatten", axis=1), [cat])
mm.add_return([flat])
```

`migraphx-driver compile flatten_bug.py`

Output:
```
terminate called after throwing an instance of 'migraphx::version_2_11_0::exception'
  what():  /workspace/flux/AMDMIGraphX/src/include/migraphx/check_shapes.hpp:253: standard: flatten: Shapes are not in standard layout
Aborted (core dumped)
```

**Comment by shivadbhavsar** [comment]
Its taking the reshape -> unsqueze and trying to replace that with a transpose. Thats okay, but the stride ends up {8, 1, 36864} instead of {8, 1, 1}. 
@pfultz2 any suggestions where the fix should be for this?

**Comment by pfultz2** [comment]
So there is a couple of things here going wrong.

First, `flatten` should accept any layout and do a copy instead of aliasing(we will need to lower it to `lazy_reshape` later on or have simplify_reshapes convert it to a `reshape`). This will fix the exception.

Secondly, we could look into updating the `shape_transform_descriptor` to output a single `reshape`. The descriptor records it as `{[1:0, 4608:1], [8:2], [1:]}` and simplifies it to ` {[4608:1], [8:2], [1:$0]}` which looks like a transpose but considering the `1` dimension we could treat it as a reshape.

However, I am not sure if thats better. With `transpose` we can fuse it across the concat:

```cpp
@1 = concat[axis=0](x,x) -> float_type, {2, 4608, 8}, {36864, 8, 1}
@2 = cos(@1) -> float_type, {2, 4608, 8}, {36864, 8, 1}
@3 = transpose[permutation={1, 2, 0}](@2) -> float_type, {4608, 8, 2}, {8, 1, 36864}
@4 = reshape[dims={4608, 16}](@3) -> float_type, {4608, 16}, {16, 1}
@5 = @return(@4)
```

Which the `concat` could be transformed into a broadcast in this case(but I assume its written this way to make the test case simpler either way, it does allow horizontal fusions).  However, if we rewrite to just a reshape we have:

```cpp
@1 = cos(x) -> float_type, {1, 4608, 8}, {36864, 8, 1}
@2 = reshape[dims={4608, 8, 1}](@1) -> float_type, {4608, 8, 1}, {8, 1, 1}
@3 = concat[axis=2](@2,@2) -> float_type, {4608, 8, 2}, {16, 2, 1}
@4 = reshape[dims={4608, 16}](@3) -> float_type, {4608, 16}, {16, 1}
@5 = @return(@4)
```

We can still do the broadcast rewrite here, but assuming the real model actually have different inputs then we need to some work to rewrite the `concat[axis=2]` to `concat[axis=0]`, but we would still need a transpose. I am thinking we could update `find_concat_transpose` to handle any shape transformations and use the `shape_transform_descriptor` to map the axes and generate the post ops.
