### ISSUE TITLE
check accuracy for fp16 convolutions between CPU/GPU

### ISSUE THREAD

**Issue by kahmed10** [ROCm/AMDMIGraphX#508]

**Comment by scxiao** [comment]
[test_conv.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4507435/test_conv.txt)

The above file shows a very simple program that can reproduce the issue. 
Just rename the .txt to .cpp and compile it, it will generate different cpu and gpu results.

One more observation. 
If we change the w shape to {1, 3, 5, 5}, the results are correct. 
If we change type to float_type, the results are also correct.

**Comment by kahmed10** [comment]
I disabled Winograd convolutions, and fp16_inception_v1 passes verify.

**Comment by scxiao** [comment]
Can I do that in onnxruntime?

**Comment by kahmed10** [comment]
Try setting the environment variable `MIOPEN_DEBUG_CONV_WINOGRAD=0` when running the program.

**Comment by pfultz2** [comment]
So I checked with miopen tests. It does pass with a max diff of 0 using miopen, but if I pass it `--generate-float` so it use float values instead of integers I get max diff of 0.046875 but the error is within the tolerance so it passes:

```
$ ./bin/test_conv2d --input 1, 16, 208, 208 --weights 32, 16, 3, 3 --pads_strides_dilations 1 1 1 1 1 1 --disable-backward-data --disable-backward-weights --verbose --half --generate-float
error: 0.000281952
Max diff: 0.046875
Mismatch at 0: -0.397461 != -0.397949
Forward convolution: ConvOclDirectFwd
Input tensor: 1, 16, 208, 208
Weights tensor: 32, 16, 3, 3
Output tensor:
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {1, 1}, {1, 1}, {1, 1},
```

It also uses `ConvOclDirectFwd` for the algorithm not winograd. It seems like the difference is due to low precision being used as it does pass when using integer values.

**Comment by mvermeulen** [comment]
Keeping open to work with MIOpen team to see what we can do to get better fp16 precision.

**Comment by aserio** [comment]
Potentially Related to [SWDEV-293792](https://ontrack-internal.amd.com/browse/SWDEV-293792)
