### ISSUE TITLE
scalar shape processing

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#519]
As we implement more feature, we meet more scenarios with the scalar shape, and we have confusion in processing the scalar shapes, and it is easy to cause bugs in adding new features. 

For now, MIGRAPHX use lens [1] and strides [0] to represent a scalar shape, which is different from the design in numpy and onnxruntime, which uses empty lens and strides. Maybe sometime later, we can change our design to be consistent with numpy and onnxruntime, and any changes we make later to follow this way.

This issue is to track the potential problem, and we can fix that systematically in MIGraphX sometime later.

**Comment by pfultz2** [comment]
Mathematically, the zero rank tensor is a scalar(see [here](https://mathworld.wolfram.com/TensorRank.html)), but in migraphx the shape describes just a multi-dimensional container of values. This makes it simple to apply pointwise operators since it can iterate over tensors and scalars the same, but requires extra care when manipulating the shape.

If we make the zero-rank shape a scalar, then that means `elements()` would return `0`, and should `size()` from `tensor_view` return `0` as well? Which would imply we couldn't iterate over scalars using a `for` loop. This may make sense, and for pointwise operators we can upgrade the shape to a tensor before we iterator over it.

The scalar and the tensor really are two different "types" mathematically. The tensor is in the vector field and the scalar is in the scalar field. As such, tensors and scalars can have different meanings semantically. So I do think its important for us to distinguish this better, and not make scalars and tensors so easily interchangeable.
